// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingListDemo.Data;

#nullable disable

namespace ShoppingListDemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240105100453_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ShoppingItemShoppingSchedule", b =>
                {
                    b.Property<int>("ShoppingItemsId")
                        .HasColumnType("int")
                        .HasColumnName("shopping_items_id");

                    b.Property<int>("ShoppingSchedulesId")
                        .HasColumnType("int")
                        .HasColumnName("shopping_schedules_id");

                    b.HasKey("ShoppingItemsId", "ShoppingSchedulesId")
                        .HasName("pk_shopping_item_shopping_schedule");

                    b.HasIndex("ShoppingSchedulesId")
                        .HasDatabaseName("ix_shopping_item_shopping_schedule_shopping_schedules_id");

                    b.ToTable("shopping_item_shopping_schedule", (string)null);
                });

            modelBuilder.Entity("ShoppingListDemo.Data.ShoppingCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_shopping_categories");

                    b.ToTable("shopping_categories", (string)null);
                });

            modelBuilder.Entity("ShoppingListDemo.Data.ShoppingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("varchar(65)")
                        .HasColumnName("currency");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("price");

                    b.Property<int>("ShoppingCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("shopping_category_id");

                    b.HasKey("Id")
                        .HasName("pk_shopping_items");

                    b.HasIndex("ShoppingCategoryId")
                        .HasDatabaseName("ix_shopping_items_shopping_category_id");

                    b.ToTable("shopping_items", (string)null);
                });

            modelBuilder.Entity("ShoppingListDemo.Data.ShoppingSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("Day")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("day");

                    b.HasKey("Id")
                        .HasName("pk_shopping_schedules");

                    b.HasIndex("Day")
                        .IsUnique()
                        .HasDatabaseName("ix_shopping_schedules_day");

                    b.ToTable("shopping_schedules", (string)null);
                });

            modelBuilder.Entity("ShoppingItemShoppingSchedule", b =>
                {
                    b.HasOne("ShoppingListDemo.Data.ShoppingItem", null)
                        .WithMany()
                        .HasForeignKey("ShoppingItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shopping_item_shopping_schedule_shopping_items_shopping_item");

                    b.HasOne("ShoppingListDemo.Data.ShoppingSchedule", null)
                        .WithMany()
                        .HasForeignKey("ShoppingSchedulesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shopping_item_shopping_schedule_shopping_schedules_shopping_");
                });

            modelBuilder.Entity("ShoppingListDemo.Data.ShoppingItem", b =>
                {
                    b.HasOne("ShoppingListDemo.Data.ShoppingCategory", "ShoppingCategory")
                        .WithMany("ShoppingItems")
                        .HasForeignKey("ShoppingCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shopping_items_shopping_categories_shopping_category_id");

                    b.Navigation("ShoppingCategory");
                });

            modelBuilder.Entity("ShoppingListDemo.Data.ShoppingCategory", b =>
                {
                    b.Navigation("ShoppingItems");
                });
#pragma warning restore 612, 618
        }
    }
}
